### ISSUE TITLE
Sub-word AMR

### ISSUE THREAD

**Issue by dungtn** [Amazing-J/structural-transformer#6]
Hi @Amazing-J ,

Again thank you for releasing the code. I have a question regarding the sub-word AMR.

In case the original word doesn't have an in-coming edge, how should we encode the AMR for the corresponding subword, e.g., the word "adjust" => "ad@@ ju@@ st" in the following example?

`(a / ad@@ ju@@ st-01 :ARG0 (g / girl@@ ) :ARG1 (m / mach@@ ine))`

Thank you!

**Comment by Amazing-J** [comment]
I think you just need to give it a specific label. e.g., "root" or "bpe".
